Adding/Implementing FizzBuzz class
rbuzzibarrios/calculator pull request #13
Opened 2020-10-29 02:34 UTC by jedv3588

Adding file FizzBuzz.php; Declaration and implementation of FizzBuzz class

2020-10-29 13:35 UTC, rbuzzibarrios requested changes
la idea es que la funcion run devuelva la cadena fizzbuzz y que esta sea utilziada en la calse calculator

2020-10-29 13:35 UTC, rbuzzibarrios commented on application/Models/FizzBuzz.php
> +    use ValidateCalculatorNumberTrait;
```suggestion
```
para qué incluir este trait si no vas a utilizar ninguna funcion de esa clase

2020-10-29 13:35 UTC, rbuzzibarrios commented on application/Models/FizzBuzz.php
> +    protected $max_number;
camel case
```suggestion
    protected $maxNumber;
```

2020-10-29 13:35 UTC, rbuzzibarrios commented on application/Models/FizzBuzz.php
> +    public function __construct(int $max_number)
revisa que todo esté en camelCase
esto es un capricho mio.. no está mal como lo pusiste.. pero el standar de codigo que configuré está hecho para camel case.. lo que todavia no he logrado ponerlo a punto, de otra forma el quality check te hubiese fallado.

2020-10-29 13:35 UTC, rbuzzibarrios commented on application/Models/FizzBuzz.php
> +
```suggestion
```

2020-10-29 13:35 UTC, rbuzzibarrios commented on application/Models/FizzBuzz.php
> +    function is_fizz_buzz($n){
fijate aqui que sugiero cambiar el nombre del parametro, si decides aplicar debes cambiarlo donde se usa
```suggestion
    public function is_fizz_buzz($number)
    {
```

2020-10-29 13:35 UTC, rbuzzibarrios commented on application/Models/FizzBuzz.php
> +
```suggestion
```

2020-10-29 13:35 UTC, rbuzzibarrios commented on application/Models/FizzBuzz.php
> +
```suggestion
```

2020-10-29 13:35 UTC, rbuzzibarrios commented on application/Models/FizzBuzz.php
> +                    $output .= "FizzBuzz"."\n";
```suggestion
                    $output .= "FizzBuzz\n";
```
prueba asi a ver si funciona

2020-10-29 13:35 UTC, rbuzzibarrios commented on application/Models/FizzBuzz.php
> +
```suggestion
```

2020-10-29 13:35 UTC, rbuzzibarrios commented on application/Models/FizzBuzz.php
> +    public function run(){
```suggestion
    public function run()
    {
```

2020-10-29 13:35 UTC, rbuzzibarrios commented on application/Models/FizzBuzz.php
> +
```suggestion
```

2020-10-29 13:35 UTC, rbuzzibarrios commented on application/Models/FizzBuzz.php
> +
```suggestion
```

2020-10-29 13:35 UTC, rbuzzibarrios commented on application/Models/FizzBuzz.php
> +
```suggestion
```

2020-10-29 20:19 UTC, jedv3588 commented on application/Models/FizzBuzz.php
> +    use ValidateCalculatorNumberTrait;
se me olvido implementar la validación para que no permita números negativos, lo hago y actualizo

2020-10-30 02:01 UTC, jedv3588 commented on application/Models/FizzBuzz.php
> +                    $output .= "FizzBuzz"."\n";
yes, it's work

2020-10-30 02:27 UTC, rbuzzibarrios requested changes
perfecto mucho mejor ahora, solo te quedan unos detalles..
pero lo que más me preocupa es que la clase Calculator no tiene implementado un metodo que llame al metodo run() de la clase FizzBuzz. Y el metodo run() debe devolver la cadena conformada, no hacer un print con el echo...

2020-10-30 02:27 UTC, rbuzzibarrios commented on application/Models/FizzBuzz.php
> +            switch(true){
```suggestion
            switch(true) {
```

2020-10-30 02:27 UTC, rbuzzibarrios commented on application/Models/FizzBuzz.php
> +        for($i = 1; $i <= $maxNumber; $i++){
```suggestion
        for($i = 1; $i <= $maxNumber; $i++) {
```

2020-10-30 02:27 UTC, rbuzzibarrios commented on application/Models/FizzBuzz.php
> +class FizzBuzz{
```suggestion
class FizzBuzz
{
```

2020-10-30 02:27 UTC, rbuzzibarrios commented on application/Models/FizzBuzz.php
> +    function is_fizz_buzz($number){
```suggestion
    public function isFizzBuzz($number)
    {
```

2020-10-30 02:27 UTC, rbuzzibarrios commented on application/Models/FizzBuzz.php
> +            echo $i." ".is_fizz_buzz($i);
```suggestion
            echo $i." ".$this->isFizzBuzz($i);
```

2020-10-30 02:28 UTC, rbuzzibarrios commented
> la idea es que la funcion run devuelva la cadena fizzbuzz y que esta sea utilziada en la calse calculator

@jedv3588 ^^^^

2020-10-30 20:40 UTC, rbuzzibarrios approved these changes
APPROVED !!!

2020-10-30 20:57 UTC, merged