Create new Divide operation in Calculator Class
rbuzzibarrios/calculator pull request #8
Opened 2020-10-24 01:57 UTC by rbuzzibarrios

Create new Divide operation in Calculator Class

2020-10-24 04:43 UTC, jedv3588 commented
@rbuzzibarrios este es un comentario global

2020-10-24 04:59 UTC, jedv3588 commented on application/models/Calculator.php
> +     * @throws \Exception
@rbuzzibarrios describir el p'q de la excepcion

2020-10-24 05:11 UTC, jedv3588 commented on application/models/Calculator.php
> +        return (float) $this->firstNumber / $this->secondNumber;
```suggestion
        return fmod($this->firstNumber, $this->secondNumber);

```
[](https://www.w3schools.com/php/func_math_fmod.asp)

2020-10-24 05:15 UTC, jedv3588 requested changes
@rbuzzibarrios esto es un request change. no se si fmod funciona solo es para practicar, investigar, jajaja

2020-10-24 18:16 UTC, rbuzzibarrios commented on application/models/Calculator.php
> +     * @throws \Exception
dime un ejemplo donde se usa poner la descripción de la excepción.
por lo general no se acostumbra  a poner la descripcion de la excepcion.. lo que se hace es hacer una excepcion.
esto es un ejemplo de un metodo de laravel

2020-10-24 18:20 UTC, rbuzzibarrios commented on application/models/Calculator.php
> +     * Calculate the division of two numbers.
```suggestion
     * Calculate the division of two numbers or throw exception if dividend is zero.
```

2020-10-24 18:54 UTC, rbuzzibarrios commented on application/models/Calculator.php
> +        return (float) $this->firstNumber / $this->secondNumber;
```
>>> fmod(34,3)
=> 1.0
>>> 34/3
=> 11.333333333333

```

2020-10-24 20:31 UTC, jedv3588 approved these changes

2020-10-25 01:22 UTC, jedv3588 approved these changes

2020-10-25 01:22 UTC, merged